Repository marcuslinde/P2, pull requests merged in 2025-04, with the labels that each got.

#172 Fetch active games and winner
  frontend/pages/game/gameHelpers/gameFunctions.js
  frontend/pages/game/gamePage/gamePage.js
  frontend/pages/startPage/startPage.js
Labels: enhancement, missing feature

#174 fix error mangler import
  frontend/pages/startPage/startPage.js
Labels: bug

#177 add winner property to game model
  backend/models/game.js
Labels: missing feature
